import type { Metadata } from "next";
import "../../styles/globals.scss";
import NavBar from "@/components/NavBar";
import ClientProvider from "@/components/ClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  }
}

export default function RootLayout({
  children,
  params: { locale }
}: Readonly<RootLayoutProps>) {
  return (
    <html lang={locale}>
      <body className="flex flex-col min-h-screen">
        <NavBar />

        <main className='flex-grow flex justify-center mt-16'>
          <ClientProvider>
            {children}
          </ClientProvider>
        </main>
      </body>
    </html>
  );
}
